# Generated by Django 5.1.5 on 2025-01-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookcomment_book_alter_bookcomment_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktracking',
            unique_together=set(),
        ),
    ]
